# Generated by Django 4.1.5 on 2023-02-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100)),
                ('encrypted_filepath', models.FileField(max_length=1000, upload_to='')),
                ('encrypted_aeskey', models.CharField(max_length=1000)),
                ('ecc_public_key', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'file_storage_tbl',
            },
        ),
    ]
