# Generated by Django 4.1.5 on 2023-02-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filestorage',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='filestorage',
            name='created_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='filestorage',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='filestorage',
            name='deleted_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='filestorage',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='filestorage',
            name='updated_by',
            field=models.IntegerField(null=True),
        ),
    ]
