# Generated by Django 4.1.5 on 2023-02-26 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_storage', '0002_filestorage_created_at_filestorage_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filestorage',
            name='encrypted_aeskey',
            field=models.BinaryField(max_length=1000),
        ),
    ]
