# Generated by Django 4.1.5 on 2023-02-26 15:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('file_storage', '0003_alter_filestorage_encrypted_aeskey'),
    ]

    operations = [
        migrations.AddField(
            model_name='filestorage',
            name='access_users',
            field=models.ManyToManyField(blank=True, related_name='access_files', to=settings.AUTH_USER_MODEL),
        ),
    ]
